site_name: NextNonce Docs
docs_dir: docs

nav:
  - Home: index.md

  - Developer:
      - Backend:
          - Installation: developer/backend/installation.md
          - Architecture: developer/backend/architecture.md
          - API Reference: developer/backend/reference.md
      - Mobile:
          #- Reference: developer/mobile/reference/README.md
          - Architecture: developer/mobile/architecture.md
          - Installation: developer/mobile/installation.md

  - User:
      - Get Started: user/get-started.md
      - FAQ:         user/faq.md


theme:
  name: material

plugins:
  - search
  - swagger-ui-tag