site_name: NextNonce Docs
docs_dir: docs

nav:
  - Home: index.md

  - Developer:
      - Backend:
          - Overview: 'developer/backend/index.md'
          - Installation: developer/backend/installation.md
          - Architecture: developer/backend/architecture.md
          - API Reference: developer/backend/reference.md
      - Mobile:
          - Overview: 'developer/mobile/index.md'
          - Architecture: developer/mobile/architecture.md
          - Installation: developer/mobile/installation.md

  - User:
      - Get Started: 'user/index.md'
      - FAQ:         user/faq.md


theme:
  name: material

plugins:
  - search
  - swagger-ui-tag