site_name: NextNonce Docs
docs_dir: docs

nav:
  - Home: index.md

  - Developer:
      - Backend:
          - Introduction: 'developer/backend/index.md'
          - Installation: 'developer/backend/installation.md'
          - API Reference: 'developer/backend/reference.md'
          - Architecture:
              - Overview: 'developer/backend/architecture/overview.md'
              - Database Schema: 'developer/backend/architecture/database-schema.md'
              - Providers: 'developer/backend/architecture/providers.md'
              - Authentication: 'developer/backend/architecture/auth.md'
              - Request Flow: 'developer/backend/architecture/request-flow.md'
      - Mobile:
          - Overview: 'developer/mobile/index.md'
          - Architecture: developer/mobile/architecture.md
          - Installation: developer/mobile/installation.md

  - User:
      - Get Started: 'user/index.md'
      - FAQ:         user/faq.md


theme:
  name: material

plugins:
  - search
  - swagger-ui-tag

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences