site_name: NextNonce Docs
docs_dir: docs

nav:
  - Home: index.md

  - Developer:
      - Backend:
          - Introduction: 'developer/backend/index.md'
          - Installation: 'developer/backend/installation.md'
          - API Reference: 'developer/backend/reference.md'
          - Architecture:
              - Overview: 'developer/backend/architecture/overview.md'
              - Database Schema: 'developer/backend/architecture/database-schema.md'
              - Providers: 'developer/backend/architecture/providers.md'
              - Authentication: 'developer/backend/architecture/auth.md'
              - Request Flow: 'developer/backend/architecture/request-flow.md'
      - Mobile:
          - Introduction: 'developer/mobile/index.md'
          - Installation: developer/mobile/installation.md
          - Architecture:
              - Overview: 'developer/mobile/architecture/overview.md'
              - UI: 'developer/mobile/architecture/ui.md'
              - Navigation: 'developer/mobile/architecture/navigation.md'
              - Result and Error: 'developer/mobile/architecture/result-error.md'
              - DI: 'developer/mobile/architecture/di.md'
              - Network: 'developer/mobile/architecture/network.md'
              - Authentication: 'developer/mobile/architecture/auth.md'
              - Reactive Flows: 'developer/mobile/architecture/flow.md'
              - Caching Strategy: 'developer/mobile/architecture/caching.md'
              - Bignum & Formatting: 'developer/mobile/architecture/bignum.md'
  - User:
      - Welcome: 'user/index.md'
      - Installation: 'user/installation.md'
      - Getting Started: 'user/getting-started.md'
      - Using the App: 'user/using-the-app.md'


theme:
  name: material
  custom_dir: docs/stylesheets
  palette:
    # Light mode (Light Purple)
    - scheme: default
      primary: 'deep purple'
      accent: 'deep purple' 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode (Deep Purple)
    - scheme: slate
      primary: 'deep purple' 
      accent: 'deep purple'  
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - swagger-ui-tag


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences