[build]
command = "mkdir -p docs/developer/backend/reference && curl -o docs/developer/backend/reference/openapi.json https://raw.githubusercontent.com/NextNonce/Backend/main/static/openapi.json && mkdocs build"
publish = "site"